title: "RCL VC Papers"
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
search_enabled: true
aux_links:
  "RCL VC Papers on GitHub":
    - "https://github.com/rcl-vc/papers"
callouts:
  information:
    title: Information
    color: blue
  warning:
    title: Warning
    color: red